trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.12.2'
  
steps:
  - checkout: self

  - script: |
      echo "Installing Terraform ${TF_VERSION}..."
      wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      unzip terraform_${TF_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -version
    displayName: 'Install Terraform CLI'
 
  - script: |
      echo "Current path : $(pwd)"
      echo "System.DefaultWorkingDirectory : $(System.DefaultWorkingDirectory)"
      echo "System.ArtifactsDirectory : $(System.ArtifactsDirectory)"
      echo "Pipeline.Workspace : $(Pipeline.Workspace)"
      find . -name '*.tf'
    displayName: 'Looking for *.tf files in the current directory'
    continueOnError: true

  - script: |      
      echo "Pipeline.Workspace: $(Pipeline.Workspace)"
      find "$(Pipeline.Workspace)" -name '*.tf' -exec echo "Found Terraform file: {}" \;
    displayName: 'Find all Terraform files in the Pipeline Workspace'

  - script: |
      terraform init -backend=false
      terraform validate
    displayName: 'Terraform Init & Validate on (CPA-Mobile-App)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/CPA-Mobile-App'
    continueOnError: false

  - script: |
      # Install TFLint latest version
      curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
      # Echo the installed version
      tflint --version

      set -e

      # Run TFLint on all Terraform folders
      for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
        echo "🔍 Running TFLint in $dir"
        (cd "$dir" && tflint --init && tflint)
      done
    displayName: 'Run TFLint (Terraform linter that focuses on finding bugs, style issues, and potential problems in your Terraform code)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/CPA-Mobile-App'
    continueOnError: false

  - script: |
      curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      tfsec --exclude azure-database-enable-audit
    displayName: 'Run tfsec (Scans your Terraform code and checks it against a large set of security best practices and compliance policies)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/CPA-Mobile-App'
    continueOnError: true

  - script: |
      pip install checkov
      checkov -d . --skip-check CKV_TF_1,CKV_TF_2,CKV2_AZURE_21,CKV_AZURE_132,CKV_AZURE_100,CKV_AZURE_140,CKV_AZURE_186
    displayName: 'Run Checkov (scans IaC files for misconfigurations, policy violations, and security risks)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/CPA-Mobile-App'
    condition: true
    continueOnError: true

  - script: |
      # echo "Fetching latest Terrascan release tag from GitHub..."
      # TERRASCAN_LATEST_TAG=$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
      # echo "Latest tag: $TERRASCAN_LATEST_TAG"
      # TERRASCAN_URL="https://github.com/tenable/terrascan/releases/download/${TERRASCAN_LATEST_TAG}/terrascan_linux_amd64"
      # echo "Downloading Terrascan from $TERRASCAN_URL"
      # curl -sSL -o terrascan "$TERRASCAN_URL"
      # chmod +x terrascan
      # sudo mv terrascan /usr/local/bin/
      curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
      tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
      sudo install terrascan /usr/local/bin && rm terrascan
      echo "Terrascan version:"
      terrascan version 
    displayName: 'Download and Install Latest Terrascan'
    continueOnError: false

  - script: |
      if [ -f /usr/local/bin/terrascan ]; then
        echo "Terrascan exists:"
        ls -l /usr/local/bin/terrascan
        file /usr/local/bin/terrascan
        echo "Terrascan version:"
        terrascan version        
      else
        echo "Terrascan does not exist in /usr/local/bin/"
      fi      
    displayName: 'Check Terrascan Installation'
    continueOnError: false

  - script: |
      echo "Scanning all Terraform subdirectories under: $(System.DefaultWorkingDirectory)"
      
      # Define rules to skip (you can add or remove IDs as needed)
      # "description": "Ensure there are no firewall rules allowing unrestricted access to Redis from other Azure sources",
      # "rule_id": "AC_AZURE_0391",
      # "description": "Anonymous, public read access to a container and its blobs can be enabled in Azure Blob storage. This is only recommended if absolutely necessary.",
      # "rule_id": "AC_AZURE_0366",
      SKIP_RULES="AC_AZURE_0391,AC_AZURE_0366"

      # Find all unique directories that contain .tf files
      find "$(System.DefaultWorkingDirectory)" -type f -name "*.tf" -exec dirname {} \; | sort -u | while read dir; do
        echo "Scanning directory: $dir"
        #/usr/local/bin/terrascan scan -t azure -i terraform -d "$dir" --skip-rules $SKIP_RULES || echo "Scan failed in $dir"
        
        # Below get the correct rule IDs by outputting the scan results in JSON format
        #/usr/local/bin/terrascan scan -t azure -i terraform -d "$dir" -o json
      done
    displayName: 'Terrascan - Scan All Terraform subdirectories (with exemptions)'
    condition: true
    continueOnError: false
